### ISSUE TITLE
Unable to trace two guzzle calls (Eg:each call in different micro service) in a single trace id 

### ISSUE THREAD

**Issue by Dipenduroy** [jcchavezs/zipkin-instrumentation-guzzle#12]
- Unable to trace two guzzle calls (Eg:each call in different micro service) in a single trace id 
- Both calls have different trace id instead of a single trace tree

> Sequence Flow

ApiGateway
    |
    HTTP CALL 
    | 
    User Subjects Api (service 1)
    |
    HTTP CALL 
    |
    User Preferences Api (service 2)

Code : 
        [https://gist.github.com/Dipenduroy/17f090d14372829ffc73faa0ec0879bb](https://gist.github.com/Dipenduroy/17f090d14372829ffc73faa0ec0879bb)      

Zipkin Dash:
![Screenshot 2020-06-02 at 7 33 23 PM](https://user-images.githubusercontent.com/5229482/83529474-03c84780-a508-11ea-85f0-a70b03ca286d.png)
Trace 1:
![Screenshot 2020-06-02 at 7 33 36 PM](https://user-images.githubusercontent.com/5229482/83529492-09259200-a508-11ea-97bb-ee4a7513806f.png)
Trace 2:
![Screenshot 2020-06-02 at 7 33 32 PM](https://user-images.githubusercontent.com/5229482/83529489-07f46500-a508-11ea-9f98-95557103b1b8.png)

**Comment by jcchavezs** [comment]
Closing as this was addressed in https://github.com/jcchavezs/zipkin-instrumentation-guzzle/issues/11#issuecomment-637743018
